steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['debug', 'source', 'gen-repo-info-file', '--output-directory', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/hello-app:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/hello-app:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - container
      - clusters
      - get-credentials
      - sample-cluster
      - --zone=asia-east1-b
      - --project=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '--filename=manifests/hello-app-deployment.yaml'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '--filename=manifests/hello-app-service.yaml'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/hello-app'
      - 'hello-app=gcr.io/$PROJECT_ID/hello-app:$REVISION_ID'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/hello-app'
